### ISSUE TITLE
Add .desktop file for usage with existing screenshots

### ISSUE THREAD

**Issue by carlos22** [gabm/satty#10]
This is a very cool tool. Would it be possible to add a desktop file so we can open already existing screenshots easily from any file browser?

**Comment by gabm** [comment]
good idea. I sketched a .desktop file and that works beautifully. Unfortunately now we need an icon :facepalm:. Any idea?

**Comment by gabm** [comment]
one of those i suppose for now: https://commons.m.wikimedia.org/wiki/GNOME_Desktop_icons

**Comment by gabm** [comment]
This has been fixed and released as v0.4.0
