### ISSUE TITLE
Hyprland keybinding is not working!

### ISSUE THREAD

**Issue by Eccys** [gabm/Satty#113]
Hi!! In Hyprland, when I bind `grim -g "$(slurp -o -r -c '#ff0000ff')" -t ppm - | satty --filename - --fullscreen --output-filename ~/Pictures/sss/$(date "+%Y-%m")/$(date "+%d-%H-%M-%S").png` to a key, it does not work. When I use it in the terminal, it works.

video demonstration: https://streamable.com/b95021

**Comment by fabolous005** [comment]
you have to escape `#` with another `#`. It should be: `grim -g "$(slurp -o -r -c '##ff0000ff')" -t ppm - | satty --filename - --fullscreen --output-filename ~/Pictures/sss/$(date "+%Y-%m")/$(date "+%d-%H-%M-%S").png`

**Comment by gabm** [comment]
I was thinking it might be something like this..Given that a large userbase is using Hyprland, maybe we could add a hint to the readme? Would you prepare a PR?

**Comment by Eccys** [comment]
Here you go: #114 \:D
