### ISSUE TITLE
[Feature request] Add freehand drawing and a way to exit selection mode

### ISSUE THREAD

**Issue by REALERvolker1** [gabm/Satty#12]
Hey there! I think this project has lots of potential.

Are there any plans to add freehand drawing? It is my main use case for swappy.

Also, when I select an area in the editor, I can't deselect. Am I missing something here?

Another suggestion would be to add a GTK color picker to the bottom color panel to choose a custom color.

Great job!

**Comment by gabm** [comment]
Thank you for your suggestions, constructive feedback is always appreciated.

As I see, there are several requests

- freehand drawing - that makes sense, i Will have a look
- selection - selection is currently only half implemented. Crop and text can be active (=selected), but the others don't have that concept. I'm future i wanted everything to be selectible and editable. Therefore a "select nothing" button is required, will implement that
- colour selection: I'm not sure about that .. the intention was to have a limited selection of attributes (5 colours, 3 sizes) to keep things simple. I'm not sure about free colour selection atm...

**Comment by REALERvolker1** [comment]
imo the color selection thing would not complicate anything, and in fact would make it much easier to use. It does not hurt the UX of Swappy, for example.

![image](https://github.com/gabm/satty/assets/73304952/1e7803cb-5787-4ba5-a351-48dc080c1d0e)

**Comment by gabm** [comment]
custom color dialog and pointer tool have been released as v0.5.0: https://github.com/gabm/Satty/releases/tag/v0.5.0

**Comment by gabm** [comment]
freehand drawing is implemented in https://github.com/gabm/Satty/releases/tag/v0.6.0


![image](https://github.com/gabm/Satty/assets/482105/a99cebf3-404e-42d5-83e8-f9edf7c8cb65)
