### ISSUE TITLE
Aarch64 appimage for install on asahi linux, fedora 

### ISSUE THREAD

**Issue by physicophilic** [gabm/Satty#120]
Hi
 
I'm using Asahi Fedora remix on a Macbook M1 which uses aarch64 packages, and it would be very nice if you can provide an appimage for aarch64. 

I don't see instructions for building from source only for Fedora, and I'm no expert at the job either. Can one build from source on Asahi Fedora Remix for this machine?

**Comment by gabm** [comment]
you should be able to build without major issues. I can help a bit, but I won't be able to maintain an aarch64 appimage, sorry. 

Best would be to try to find out, how packages are maintained in Asahi and how you can submit new packages...
