### ISSUE TITLE
satty-bin no longer in AUR

### ISSUE THREAD

**Issue by nickconway** [gabm/Satty#122]
The satty-bin package is no longer available from the arch user repository, but the readme still shows it as the package to install. Was this intentional?

**Comment by gabm** [comment]
I got a short notification, that satty has been moved to extra and will not been provided through the official repositories.  As part of this move, they removed the aur package.

installing `satty` through pacman is now the official way! That means we got enough votes and downloads - great news! 🎉

I didn't have time to either celebrate that milestone nor adjust the readme so far. If you want, you can provide a PR ;0
