### ISSUE TITLE
Pasting doesn't work

### ISSUE THREAD

**Issue by Permafrozen** [gabm/Satty#128]
Hello, I really like this screenshot utility, but sadly trying to paste images doesn't work. I am on Hyprland, and everything works right, saving also works, just pasting doesn't work.

When pasting in a terminal it says "�PNG", so something seems to be pasted, but if I try to paste in discord, or any other app, nothing happens.

I hope this isn't because of some mistake I made.

**Comment by gabm** [comment]
I dont know whether your issue still exists, but without any additional information about your setup, the copy-command etc. I am not able to do anything here.

Feel free to re-open with more information.
