### ISSUE TITLE
Adding Cargo.lock to repository

### ISSUE THREAD

**Issue by ElysaSrc** [gabm/satty#13]
Hello,

I'm trying to package Satty for NixOS, but it requires the `Cargo.lock` file.
As the documentation says:

> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put Cargo.lock in your .gitignore. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git. If you’re curious about why that is, see [“Why do binaries have Cargo.lock in version control, but not libraries?” in the FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).

(Source: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)

If I'm understing this correctly we fall under the case on which we should have a `Cargo.lock` commited.

Once you make a release with this file I'll be happy to package it for NixOS.

**Comment by gabm** [comment]
Thanks for volunteering to bring Satty to Nix, highly appreciated.

I will make sure you include a Cargo.lock in the next release!

**Comment by gabm** [comment]
here you go: https://github.com/gabm/satty/releases/tag/v0.4.0
