### ISSUE TITLE
[Bug] Crop output is resampled and blurry

### ISSUE THREAD

**Issue by TheBoctor** [gabm/Satty#131]
When opening any image with Satty and cropping it, the result is always blurry. I could not find any mentions of blurriness nor resampling, in the existing issue reports.

This is best demonstrated with bitmapped fonts or small, aliased graphics like sprites.
Before Satty crop:
![image](https://github.com/user-attachments/assets/b78bce59-4cec-427a-a260-782a16217573)
After Satty crop:
![image](https://github.com/user-attachments/assets/820a822d-93b2-49b4-b260-644d02ab452d)

Do the cropping tool's bounds use whole integers and quantize to match the input file's pixel grid? When I tested with a very small image, the cropping bounds could be dragged to all kinds of fractional positions.

**Comment by pinarruiz** [comment]
Noticed this too, screenshots of text look very bad:

![image](https://github.com/user-attachments/assets/45f84662-f210-4dd6-9be7-421077ca5346)

**Comment by gabm** [comment]
thanks to @pol-rivero that should be fixed in v0.16.0

**Comment by pol-rivero** [comment]
Nice :)
