### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by Alsan** [gabm/Satty#14]
There is an error "Error while saving file: Falled to save the texture as png" when pressing the save button. Also, there're two warning message as following:

![2023-11-12_10:39:37](https://github.com/gabm/Satty/assets/217947/32f4701d-c86d-47b3-8f55-5fe7d6539ee1)

My system infoation:

![2023-11-12_10:42:23](https://github.com/gabm/Satty/assets/217947/34b47901-594f-4e98-9510-353a677b7199)

Please info me if any further information is needed.

**Comment by gabm** [comment]
thank you for your big report.. that might be a tough one :/

I guess I'll need to add more information output in this case...

**Comment by gabm** [comment]
just a stupid question: might it have something to do with the parth?

could you specify `/tmp/out.png` as output filename and test again?

**Comment by gabm** [comment]
do you feel comfortable compiling satty yourself? I pushed a commit with a different saving strategy that should give more output... 4973d272676522734fc9ef35513915f87de7a728

**Comment by gabm** [comment]
after the release of 0.6.0, there is no need to build yourself

**Comment by Alsan** [comment]
Ok, I built it myself, and it works great, thanks.
