### ISSUE TITLE
make install compatibility with sudo and root not having cargo

### ISSUE THREAD

**Issue by RobertMueller2** [gabm/Satty#15]
- My cargo is installed to `$HOME/.local/bin` via rustup, root doesn't have it.
- if I want to install satty to `/usr/local`, I need root to do that.
- install depends on build-release, so `make install` includes `cargo build --release`, which root can't do.

Of course, I can use `make build-release; touch build-release; sudo make install; rm build-release` as a workaround. Or install cargo for root, of course. But it'd be nice if I didn't have to. ;)

I think the easiest is to have install depend on the actual file target/release/satty instead of build-release.

**Comment by gabm** [comment]
thanks for your report. I agree that this is suboptimal.

I am not very experienced with makefiles, could you create a pr?

**Comment by RobertMueller2** [comment]
Of course, happy to do so. Might take a few days before I find some spare time. :)

**Comment by gabm** [comment]
fixed in #16
