### ISSUE TITLE
Clipboard save doesn't seem to be picked by `wl-paste`

### ISSUE THREAD

**Issue by marcosnils** [gabm/Satty#19]
:wave:  thx for building satty, it's super useful.

I'm using cliphist (https://github.com/sentriz/cliphist) as a history manager and the way that its instructions recommend setting it up is via `wl-paste --watch cliphist store`

I've noticed that when using satty, `wl-paste --watch` doesn't catch things that are being copied into the clipboard by it. Not sure what's missing here but a possible solution could be to allow sending the output to stdout so I can pipe it to `wl-copy`. I just did a quick test myself by commenting this validation https://github.com/gabm/Satty/blob/main/src/sketch_board.rs#L157-L164 and then doing `satty -- output-filename /dev/stdout | wl-copy` and that worked.

**Comment by gabm** [comment]
yeah.. this is bugging me a bit.. there are multiple issues with clipboard in wayland 

- if no history/persistance daemon is used, clipboard is lost on program exit
  - I use clipmon, but it has its issues too
  - afaik, cliphist might have issues with some mime types - maybe thats the issue here?
-  there is an inherent race condition where the program needs to stay alive long enough for a clipboard persistence daemon to read the data

The strategy you describe sounds good, maybe we can use `--output-filename -` for stdin similar to `--filename -` for stdout?

There are some things to take care of though:

- what about logs, do they need to go to stderr then?
- if stdout is used, its the same as "no filename specified", meaning the "save to file" action is not available somehow.. or is it? .. mode confusion ;)

**Comment by ystyle** [comment]
I solved this way
```config
# watch image and store
exec-once = wl-paste --type image --watch cliphist store

# shift + super + v , show  clipboard history, and select item will copy
bind = SUPER_SHIFT, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
```

**Comment by marcosnils** [comment]
> I solved this way

this works, but seems like it doesn't with `--early-exit`. 

Good thing is that the `/dev/stdout` approach works with early-exit

**Comment by marcosnils** [comment]
> There are some things to take care of though:
> 
> * what about logs, do they need to go to stderr then?

I'd say so. 

> * if stdout is used, its the same as "no filename specified", meaning the "save to file" action is not available somehow.. or is it? .. mode confusion ;)

Maybe if no flag specified still render the "save" option and make it output via stdout by default. If you want to redirect it to a file, add the `--output-filename` flag. This way you don't break backwards compatibility and/or make the `--output-filename` flag confusing.

**Comment by gabm** [comment]
or even remove the output option and always write to stdout - and always read from stdin...

**Comment by gabm** [comment]
do you feel like giving it a shot for the dash option to write to stdout?

**Comment by marcosnils** [comment]
> do you feel like giving it a shot for the dash option to write to stdout?

sure, been wanting to find an excuse to write some rust code. You'll have to bare with me since I haven't done any rust before.

**Comment by marcosnils** [comment]
> do you feel like giving it a shot for the dash option to write to stdout?

is the dash used for stdout though? Isn't it better to make  stdout by default?
So `satty --filename -` would take the file through stdin and then automatically save via stdout.

**Comment by gabm** [comment]
I am not 100% convinced of this unfortunately. What happens if the user presses "save" twice? then wl-copy will not work I suppose?

What about fixing the core-problem by using: https://github.com/YaLTeR/wl-clipboard-rs/? That provides a way to fork a daemon that stays alive and serves the data until someone else copies something in the system.

**Comment by marcosnils** [comment]
> I am not 100% convinced of this unfortunately. What happens if the user presses "save" twice? then wl-copy will not work I suppose?

every time the user presses save, it'll write to stdout each image. It's actually quite convenient since if you do: `satty | wl-copy --type image`, each time you press save, the "last" modified image will be in the clipboard.

**Comment by marcosnils** [comment]
> Still, I would ask you to trigger that option by providing `-` as argument

thing is that using `-` to indicate that something is sent to stdout is really confusing. `-` at the end of a command is generally used to indicate that the arguments that the commend will expect will be sent through `stdin`.. 
I'm not sure about this.

**Comment by gabm** [comment]
Okay.. understood. I did read about best practices for this, for example this: https://clig.dev/#output. The bottom line is

- you can write to stdout by default if it is not a tty. That would only enable writing to stdout in case its part of a pipeline. I think this check is still missing in #20, right? All log messages should go to stderr in this case.
- other options I found went intot he direction of your initial suggestion: `--output-filename /dev/stdout`. That is nice and explicit...
- I did not find any resource talking about the meaning of `-` in in-/output arguments, but maybe I just didnt search the right place.. My motivation to discuss that was "being explicit" and avoid cluttering stdout when the user does _not_ want it. From that point of view its identical to `--output-filename /dev/stdout` and solves the same problem as the "tty check".

**Comment by marcosnils** [comment]
> * send all log to stderr - or at least create an issue for it :)

I can do this. That should be a quick change. Thx for coming back to this one.

> * I did not find any resource talking about the meaning of `-`

found an article that explains has a reasonable explanation: https://www.baeldung.com/linux/dash-in-command-line-parameters.

**Comment by gabm** [comment]
thanks for the link.. unfortunately (for you) it even supports my point

> As we can see, we used the “-” for both stdin and stdout. It’s up to the command itself to interpret it accordingly.

but again: no strong feelings

**Comment by gabm** [comment]
for now this became stale.. pls re-open if you feel like it
