### ISSUE TITLE
Preselect `crop` like flameshot

### ISSUE THREAD

**Issue by TD-Sky** [gabm/Satty#21]
I use such command to capture screen area like flameshot in hyprland:

```nu
# nushell
grim -o (hyprctl monitors -j | from json | where focused | first | get name) - | satty -f - --fullscreen --output-filename $saved
```

But unlike flameshot, the default operation of satty is `Pointer` so I have to choose `Crop` and then crop the area. It takes more steps.

Are there any plans to support preselecting mode in command line or changing the default operation of satty?

**Comment by gabm** [comment]
Indeed, the crop tool was default before the pointer tool was introduced. Then I figured that the pointer was a more sane default.

So I guess the easiest is to introduce an option to choose the default. I personally would also be fine to switch it to the crop tool but i am almost sure we will get this request for the other tools at some point...

Would you want to give it a shot?

**Comment by gabm** [comment]
Apart from that I also want to introduced hotkeys for choosing the tools and options at some point - but that will only be a half-solution

**Comment by TD-Sky** [comment]
I'm not familiar with GTK but can give a try.

**Comment by TD-Sky** [comment]
Implement in this PR: https://github.com/gabm/Satty/pull/22
