### ISSUE TITLE
Cargo.lock is out of date in v0.8.0

### ISSUE THREAD

**Issue by DerpDays** [gabm/Satty#27]
For the release v0.8.0, the Cargo.lock file is not in sync with the dependencies in Cargo.toml which makes it hard to package, i suggest maybe creating a new release v0.8.1 which includes the newly updated Cargo.toml?

For example in v0.8.0:
Cargo.toml (clap v4.4.4) - Cargo.lock (clap v4.4.7)
Which are out of sync

Whereas this is resolved in the latest git commit 891b4e9
latest git (clap v4.4.10 in both Cargo.{lock,toml})

**Comment by gabm** [comment]
I released v0.8.1. Can you confirm that this works?

are you aware of/working on: https://github.com/gentoo/gentoo/pull/33908?

**Comment by DerpDays** [comment]
It works on 0.8.1, though i got the dependencies from the git last time which where different (not sure why i didnt realise until today) which was why it wasn't working on 0.8.0 so, sorry about that. I just rechecked with 0.8.0 with dependencies from the tarball and it worked.

I was just creating a local updated ebuild which i do for packages if i use if i happen to see they have an update which hasn't been updated in a repo yet.

**Comment by gabm** [comment]
So i think this is fixed... thank you for your report.
