### ISSUE TITLE
Image are not copied to clipboard when using `--early-exit`

### ISSUE THREAD

**Issue by wangyc-pers** [gabm/Satty#28]
Hello,

I really appreciate some of the recent updates you've made. However, when I open an image using the `--early-exit` parameter and click the copy button, Satty exits successfully. But when I try to paste, I notice that the image is not available in the clipboard. I'm not sure if this is a bug, but if it is, I would appreciate it if you could fix it. 

Here are the details of my system:
- Operating System: Manjaro Linux Linux 6.1.64-1-MANJARO
- Desktop Environment: Gnome 45.1
- Satty Version: 0.8.0

The command I'm running is:

```
gnome-screenshot -a -f /tmp/screenshot.png && satty --filename /tmp/screenshot.png --early-exit --init-tool rectangle
```

**Comment by gabm** [comment]
Thank you for your bugreport.. there are some issues with clipboard on wayland. Please see #26 for analysis and #19 for another instance.

---

As you use v0.8.0, you might be able to make use of the new copy-command option: `--copy-command wl-copy`. `wl-copy` is a utility that does persistance...

Further, if you can ask gnome-screenshot to send the image to the pipe/stdout, you can pipe that directly into satty without writing it to disk by specifying `--filename -`.

**Comment by wangyc-pers** [comment]
Thank you very much. When I added the `--copy-command 'wl-copy'` parameter, the image could be correctly copied to the clipboard.
gnome-screenshot does not support sending image to pip/stdout. I have tried many screenshot tools like grim, maim, scrot, but the only one that works properly is gnome-screenshot.

I am now using Satty instead of flameshot. flameshot stopped working properly after the Manjaro rolling update, but Satty has been able to perfectly meet my daily needs. 

By the way, I would like to ask if there are any plans to configure the default color and size in the future.

**Comment by wangyc-pers** [comment]
I think it would be beneficial to add a configuration file in either JSON or TOML format. 
This would allow users to customize various settings such as default tools, colors, sizes, and whether to exit after copying. 
By doing so, we can avoid cluttering the parameters and potentially add a settings interface for Satty in the future. 
This is just my personal opinion, and I'm not very familiar with Rust and client development.

**Comment by gabm** [comment]
and what about a GUI to configure things? after all its a GUI application? Wouldn't that ease the boundary of entrance for new users?

**Comment by wangyc-pers** [comment]
I think that a GUI configuration interface would be more user-friendly and easier to use for new users. However, at this moment, I believe we can skip considering the GUI configuration.
Currently, the configurations I can think of are default size and color related to personal preferences.
It would be better to allow users to configure these settings, either through parameters or a configuration file.
If there are new features added in the future, there might be a need for additional configurations.
For example, if we add a feature that allows users to upload pictures to the server, we might need to configure the file server's address, username, password, etc.
This functionality would be beneficial when writing markdown documents. Nevertheless, I'm not sure if you have plans for these features.
These discussions seem unrelated to this issue, so perhaps we can open a separate issue to discuss them.

I think Satty is great, and I'm very happy to use it. It's user-friendly. I'm already a heavy user. Thanks a lot!

**Comment by gabm** [comment]
okay.. thanks for your thoughts!
