### ISSUE TITLE
Request the function to draw numerical serial numbers

### ISSUE THREAD

**Issue by ystyle** [gabm/satty#3]
Request the function to draw numerical serial numbers

**Comment by gabm** [comment]
interesting.. can you draw a mock-up and explain what this will be useful for?

**Comment by ystyle** [comment]
like this (flameshot, bug not work in hyprland), Mainly used to mark the order of content that requires attention
![截图_2023-10-19_151030](https://github.com/gabm/satty/assets/4478635/ece60a04-4dad-4514-b261-82b757ed51ba)

**Comment by gabm** [comment]
yep, I think that makes sense. I might have a look into it.. I would also be happy for a contribution, I can guide you if you want.

---

I see that this question might come up more often: "can you implement Feature X from Flameshot?". Maybe we could collect Flameshots Featureset and rank their usefulness/simplicity. While we could implement everything, I want to keep the tool as simple as possible..

**Comment by gabm** [comment]
still WIP.. what do you think?

**Comment by ystyle** [comment]
It looks pretty good

**Comment by gabm** [comment]
This has been released as v0.2.0...
