### ISSUE TITLE
Feature request: Marker/lines thickness

### ISSUE THREAD

**Issue by mjollnir14** [gabm/Satty#35]
Would be nice to chose from different thickness for drawing tools, 1 pixel is very thin on full screen captures

**Comment by gabm** [comment]
thanks for your report.. there are 3 sizes you can choose from right now (S,M and L). They do apply to all tools and change line widths, text sizes, marker diameters and so on.

Is this what you are looking for?

Further we plan to implement a configuration option to customise the default sizes, as we do recognise that the default probably doesn't fit all. See #30 for more details. Contributions are always welcome to push things forward.

**Comment by mjollnir14** [comment]
Oh you are correct!

Actually I might be using a resolution a bit high that I didn't notice the difference between the 3 sizes. Maybe instead of a fixed pixel size we could use:

- Small = biggest pixel count (horizontal vs vertical) * .01
- Medium = biggest pixel count (horizontal vs vertical) * .03
- High = biggest pixel count (horizontal vs vertical) / *.06

**Comment by gabm** [comment]
As part of release [v0.9.0](https://github.com/gabm/Satty/releases/tag/v0.9.0) we now have a new setting called `annotation-size-factor` that allows you to manually increase/decrease the annotation's sizes. Let me know what you think.

I consider this issue closed - if you want to re-open it: go ahead!
