### ISSUE TITLE
Ubuntu issue

### ISSUE THREAD

**Issue by yermulnik** [gabm/Satty#36]
I've downloaded latest release of `satty` and attempted to try it:
```shell
> fgrep -w VERSION /etc/os-release
VERSION="22.04.3 LTS (Jammy Jellyfish)"

> ./satty
./satty: symbol lookup error: ./satty: undefined symbol: gtk_color_dialog_choose_rgba_finish
```

From README I can see it requires `libgtk-4-1` and `libadwaita-1-0`, whilst both are installed:
```shell
> dpkg -l libgtk-4-1 libadwaita-1-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version                   Architecture Description
+++-====================-=========================-============-==========================================
ii  libadwaita-1-0:amd64 1.1.7-0ubuntu0.22.04.1    amd64        Library with GTK widgets for mobile phones
ii  libgtk-4-1:amd64     4.6.9+ds-0ubuntu0.22.04.1 amd64        GTK graphical user interface library
```

I'm on non-WL desktop if it does matter.

**Comment by gabm** [comment]
I'm sorry to hear that you have problems. Indeed your version of gtk is too old, we need 4.10 at least. 

nevertheless, I think we should make it a policy to support the latest Ubuntu LTS or older. I will check what can be done to lower the requirement.

**Comment by yermulnik** [comment]
@gabm Appreciate it 👍🏻

**Comment by gabm** [comment]
can you confirm that v0.8.3 works for you now? https://github.com/gabm/Satty/releases/tag/v0.8.3

I think we will keep supporting 22.04 for some time after 24.04 gets released to give users time to switch...

**Comment by yermulnik** [comment]
> can you confirm that v0.8.3 works for you now? [`v0.8.3` (release)](https://github.com/gabm/Satty/releases/tag/v0.8.3)

Yep, it works. Thanks.
