### ISSUE TITLE
Satty does not copy or save screenshots on Arch Linux with Sway

### ISSUE THREAD

**Issue by billy54** [gabm/satty#4]
I installed Satty using trizen, a lightweight AUR helper, then bound $mod+Shift+s to the command provided in the readme. This does give me a screen to select the capture area and then goes to the editing screen, but the save or copy buttons do not work. If I try to quit the application with $mod+Shift+Q, nothing is added to the clipboard or saved anywhere. Can anyone help me fix this issue?

**Comment by gabm** [comment]
thank you for your feedback...

- saving only works, if you specify a folder via the command-line. After pressing the save button, you should find the file there
- copying should work, but by default the clipboard in wayland is only kept as long as the sending application (in this case satty) is still open. Once satty exits, the clipboard is destroyed. You need a program that keeps the clipboard active, for example [Clipmon](https://git.sr.ht/~whynothugo/clipmon) or others

You can run satty manually on the commandline, use the same command as you bound to $mod+Shift+s. If there is any error, it will be printed there...

**Comment by billy54** [comment]
Ah, I see the issue now. Satty did actually save the files, and the clipboard issue is just my own fault of not configuring it properly. I guess this issue can be closed now
