### ISSUE TITLE
FR: Add a Highlighter tool

### ISSUE THREAD

**Issue by sdooweloc** [gabm/Satty#41]
Loving this utility currently but it would be many times better with the addition of either a block or freeflow highlighter tool to overlay a semitransparent color line over things instead of being restricted to pen and other drawing options for bringing attention.

**Comment by gabm** [comment]
Sounds good.. Do you want to take a shot?

Also: are there techniques to increase the contrast in highlighted areas?

**Comment by DerpDays** [comment]
I'd be happy to take a shot at this.

**Comment by gabm** [comment]
cool, please take a shot

**Comment by gabm** [comment]
@sdooweloc could you have a look at #72 and give your comments?

**Comment by sdooweloc** [comment]
I'll give it a look later today!

**Comment by gabm** [comment]
released as https://github.com/gabm/Satty/releases/tag/v0.12.0
