### ISSUE TITLE
add tooltips

### ISSUE THREAD

**Issue by noornee** [gabm/satty#5]
Hiya!
I came across your satty post from a month ago on the swaywm subreddit and decided to give it a try. I love it!

##  issue
when i installed satty, I briefly looked at the GIF that was uploaded in the Readme and ran the sample usage command. I got a bit confused cos I couldn't tell what some of the buttons signified. It would be awesome if a tooltip was added.

## solution
I'm not well experienced with rust. I actually never completed the rust book :/ (i suppose it's about time for me to pick it back up ^^)

anyhoo, adding a tooltip seemed like a relatively easy thing I could do to contribute to this project, so I did. I would create a PR that resolves this issue in a sec and I would greatly appreciate your feedback if I didn't do something right. Thank you!

**Comment by gabm** [comment]
thanks for the warm words! 

Tooltips would be useful, I agree.. I will consider for next version ;)

(If you want to give it a try yourself, go ahead.. I won't judge anyone... though I'm an experienced programmer, I'm new to rust and gtk myself...)

**Comment by noornee** [comment]
You're welcome and Thanks for your swift response ^^

>(If you want to give it a try yourself, go ahead.. I won't judge anyone... though I'm an experienced programmer, I'm new to rust and gtk myself...)

Alrightt, i just created a PR for it

**Comment by gabm** [comment]
fixed by #6
