### ISSUE TITLE
Call for Testers - OpenGL Backend

### ISSUE THREAD

**Issue by gabm** [gabm/Satty#55]
Hi everyone,

the new opengl backend has been coming for a long time! It is supposed to improve the responsiveness considerably - even when using high-resolution images. This will also solve problems with tools that require a high number of redraws - like the brush.

The changes have been proposed here: https://github.com/gabm/Satty/pull/53. We need to test them, as the change is quite fundamental. 

Please build this branch locally and report any problems w.r.t. the current releases. If you need prebuilt binaries, we can certainly provide them..

**Comment by Iss-in** [comment]
thanks for the tool, i tried the latest build on sway-git/wlroots-git 

encountered weird behavior in following steps:

1. grab a portion of screen via 'grim -g "$(slurp)" - | wl-copy --type image/png  '
2. paste it into a file , 'wl-paste > test.png'
3. open via satty , ' satty -f test.png' 

original image
![image](https://github.com/gabm/Satty/assets/36916613/b2b66c05-c1aa-41dc-93f1-3db4ea6df4fc)

image in satty 
![image](https://github.com/gabm/Satty/assets/36916613/250285d4-f37c-42a4-9fed-3112ebcbe821)

**Comment by gabm** [comment]
thanks for this report. That was a problem with stride.. I created an issue for femtovg [here](https://github.com/femtovg/femtovg/issues/201) and implemented a workaround. 

Can you test again?

**Comment by Iss-in** [comment]
thanks seems fine now

**Comment by gabm** [comment]
This has been released as `0.11.0`. 

**ATTENTION Packagers**: This release drops the dependencies `cairo` and `pango`. At the same time it introduces new dependencies for `libepoxy` and `libGL`.

/cc @TD-Sky @MrDuartePT @sodface @r-ryantm

**Comment by TD-Sky** [comment]
`satty-bin` 0.11.0 has been released in AUR.

I'm confused why `ldd` still finds `libcairo` and `libpango` which should be dropped linked by satty.
