### ISSUE TITLE
Occasional corrupted screenshot

### ISSUE THREAD

**Issue by billy54** [gabm/Satty#59]
Sometimes when I take a screenshot it ends up looking like this:

![image](https://github.com/gabm/Satty/assets/95737359/faa97ae4-a216-4193-88f3-233c1814ab27)

I am not sure whether this is an issue with Satty or something else, but I'll post it here anyway.

The bug appeared when I updated recently. It did not occur before. It seems to occur less if I try to completely stop my mouse before releasing the selection tool (I use a trackpad)

This is the command I am using (modified from the one in the readme)
```
grim -g "$(slurp -o -c '#ff0000ff')" - | satty --filename -
```
My config:
```
[general]
# Start Satty in fullscreen mode
fullscreen = true
# Exit directly after copy/save action
early-exit = false
# Select the tool on startup [possible values: pointer, crop, line, arrow, rectangle, text, marker, blur, brush]
initial-tool = "brush"
# Configure the command to be called on copy, for example `wl-copy`
copy-command = "wl-copy"
# Increase or decrease the size of the annotations
#annotation-size-factor = 2
# Filename to use for saving action. Omit to disable saving to file. Might contain format specifiers: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
output-filename = "/home/redacted/Pictures/Screenshots/satty-%Y%m%d-%H:%M:%S.png"
# After copying the screenshot, save it to a file as well
save-after-copy = false
# Hide toolbars by default
default-hide-toolbars = false
```

I am using Hyprland on Artix Linux, installed package through AUR. Any help would be appreciated, or at least a direction to the correct place that I should file this issue. Thanks

**Comment by gabm** [comment]
are you using v0.11.1? there was a regresion in 0.11.0 that caused exactly this kind of pattern...

**Comment by Ligthiago** [comment]
I can confirm that this problem occurs randomly with the above command even in v0.11.1. It is not 100% reproducible, sometimes it works normally.

![image](https://github.com/gabm/Satty/assets/142721811/95c04e6f-79fc-41a5-804e-db3a7724806b)

**Comment by gabm** [comment]
or like this

```
grim -g "$(slurp -o -c '#ff0000ff')" - > /tmp/test.png && satty --filename /tmp/test.png
```

**Comment by Ligthiago** [comment]
I already send a sample of picture that looks normal in previous comment (first link), but here is another one
![test](https://github.com/gabm/Satty/assets/142721811/e77a9205-35b4-430d-b2de-88a92fa3d720)

In satty in looks like this

![image](https://github.com/gabm/Satty/assets/142721811/c01bdd38-85e2-4803-8f80-ee93d2e4babc)

**Comment by qdii** [comment]
+1 I'm also affected by this 
![satty-bug](https://github.com/gabm/Satty/assets/1086125/297e1969-c9b1-42de-987e-8a4547920120)

**Comment by gabm** [comment]
does this effect occur already in editing/live view or only manifest when copying to clipboard or writing to file?

**Comment by qdii** [comment]
It happens already in the editing/live view.

**Comment by gabm** [comment]
I did find the bug and fixed it here: https://github.com/gabm/Satty/pull/60. Changes are also in main.

Can you please test again?

--

Note to self: the imgref crate (used by femtovg) is very limiting. Its abstractions do not work well.

**Comment by Ligthiago** [comment]
Seems fixed to me

**Comment by gabm** [comment]
This has been released as https://github.com/gabm/Satty/releases/tag/v0.11.2. Thanks to everyone involved!
