### ISSUE TITLE
Text tool produces broken text

### ISSUE THREAD

**Issue by phuhl** [gabm/Satty#62]
Hey, nice tool! Found a bug though:

I tried to save to a file and added the text "Thats how they get you" but this was produced:

![image](https://github.com/gabm/Satty/assets/16835755/92bb20e9-a270-4c09-967d-c85ffbe67baa)

$ satty --version
satty 0.11.2

Arch Linux 6.7.9-arch1-1 on Latest Niri wm

**Comment by gabm** [comment]
thank you for your report! that doesn't look right :/

can you send me the input image?

**Comment by phuhl** [comment]
Here is a set of input image and result. I noticed, that it apparently only happens when using the crop tool first.

Input:
![screenshot-2024-03-15_10:57:38](https://github.com/gabm/Satty/assets/16835755/ca724947-ede0-4fe3-9729-1cccfd7c515c)

Satty output:
![screenshot-2024-03-15_10:59:33](https://github.com/gabm/Satty/assets/16835755/5505fa88-3909-4df9-b70e-ef96ec7e215f)

**Comment by gabm** [comment]
thanks

> I noticed, that it apparently only happens when using the crop tool first.

I think that helps! I will take a look

**Comment by gabm** [comment]
this should be fixed in https://github.com/gabm/Satty/releases/tag/v0.11.3. Can you please confirm?
