### ISSUE TITLE
Satty doesn't seem to work with grimblast (Hyprland utility)

### ISSUE THREAD

**Issue by UnixLudi0** [gabm/Satty#66]
As I know grimblast using grim and slurp, so I don't know why this happen:
Maybe I'm doing something wrong?
![image](https://github.com/gabm/Satty/assets/95374315/c3d75055-2336-4727-aa84-028d39fd00ad)
![image](https://github.com/gabm/Satty/assets/95374315/27521ada-1a7c-42df-b597-bbb289fcf902)
![image](https://github.com/gabm/Satty/assets/95374315/3995029d-0e68-4378-9f45-43ceb1cd2cf4)

**Comment by gabm** [comment]
apparently grimblast does produce a file format that satty can't read. I am a bit surprised, but lets have a look.. can you send me a sample?

`grimblast copy screen - > outputfile`

**Comment by gabm** [comment]
I just had a look at the source code of grimblast... you are using it wrong.

The help for `copy` states: "Copy the screenshot data into the clipboard.". That is not what you want! You want to use `save`: "  "Save the screenshot to a regular file or '-' to pipe to STDOUT.". So your fixed command is:

`grimblast save - | satty -f -`

**Comment by ShadowS0ng** [comment]
` grimblast save area - | satty --filename -
`
it works without problems for me

**Comment by taylorcoffelt** [comment]
Interesting, I'm getting the following with that:
```
$ grimblast save area - | satty --filename -
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
Error: Unrecognized image file format
Error: Unrecognized image file format
```

Looks more like a grim / grimblast issue:
```
$ grim -g "$(slurp -o -r -c '#ff0000ff')" -
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```
---
```
$ grim
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```

**Comment by gabm** [comment]
looks like .. maybe we can support them but opening an issue there - or better - fixing it?
