### ISSUE TITLE
can't exit

### ISSUE THREAD

**Issue by cabiste69** [gabm/satty#7]
after selecting an area to screenshot i can't exit the tool. I tried pressing ESC didn't work, tried to press the save button didn't work either and resorted to kill the process.

I'm on Arch, Hyprland.

**Comment by gabm** [comment]
Hey.. That is to be expected atm, but bad UX imho... Currently I exit the window via "kill" as well...

Which behaviour would you expect/prefer?

**Comment by cabiste69** [comment]
i think 
ESC -> exit without saving / copying
Return / Enter -> can be bound to either copy to clipboard or save and can be set in the configs

also add a copy button and a save button at the top.

*I'd love to help but i never touched rust*

**Comment by gabm** [comment]
Thank you for your feedback

- ESC for exit without saving makes sense to me, is implemented
- Enter for clipboard or save .. not sure, ctrl-c and ctrl-s feel more natural.
  - would the app exit after that operation?

**Comment by cabiste69** [comment]
i wasn't aware of the ctrl + c / s shortcut, I just personally prefer the return button but i guess it's not needed then.
also whether the application should exit or not should be a setting in the config (that's what swappy does and i find it nice)
thank you :D

**Comment by gabm** [comment]
ESC (exit without saving), Ctrl-S (file save) and Ctrl-C (copy) have been implemented as well as the `--early-exit` commandline option. 

At the moment we do not have a concept for the settings (e.g. no settings file, no GUI to edit settings) but everything is configured through cmdline.. that might or might not change in future.
