### ISSUE TITLE
[Feature Request] - Freeze Option

### ISSUE THREAD

**Issue by jasper-at-windswept** [gabm/Satty#70]
Can you please add a option to satty that freezes the screen when taking a screenshot using the `grim` command in the README?

This is a feature I haven't seen in any screenshot tool for Wayland.

**Comment by gabm** [comment]
thanks for the suggestion. That might be nice, but currently satty only processes images - it does not take the screenshots itself or interacts with wayland or the window manager in any way. that means your request is currently out of scope.

What you can do is taking a screenshot with grim right away - without using slurp for selection. That should give you the requested behaviour.

**Comment by gabm** [comment]
there is grimblast for hyperwm

**Comment by jasper-at-windswept** [comment]
> there is grimblast for hyperwm

Oh awesome thank you very much!
