### ISSUE TITLE
[Feature Request] Start multiple instances of satty

### ISSUE THREAD

**Issue by 00-kat** [gabm/Satty#84]
### Current behaviour
Currently, if you run, `satty -f img1.jpg`, it will work as expected. Now, if you run `satty -f img2.jpg` (maybe opening img1.jpg in multiple sattys would be undesirable, but I think any check that may possibly be implemented should be bypassable), nothing happens, except for waiting 1-2 seconds.

### Requested behaviour
`satty -f img1.jpg` opens a Satty, `satty -f img2.jpg` opens a second Satty.

If `img1.jpg` is opened twice, either:
  - It opens a new Satty, no questions asked;
  - It gives an error in the terminal and says use some option to bypass it;
  - It asks what to do in the GUI (preferred). Of course, if the file is `-` (i.e. standard input), it should just open a new Satty with no questions asked.

**Comment by gabm** [comment]
I agree! it should be possible to have more than one instance
